# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/qwe/Desktop/Re_storj/storjtest/Storj_local

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/qwe/Desktop/Re_storj/storjtest/Storj_local

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/qwe/Desktop/Re_storj/storjtest/Storj_local/CMakeFiles /home/qwe/Desktop/Re_storj/storjtest/Storj_local/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/qwe/Desktop/Re_storj/storjtest/Storj_local/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named storj_emulator_scan

# Build rule for target.
storj_emulator_scan: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 storj_emulator_scan
.PHONY : storj_emulator_scan

# fast build rule for target.
storj_emulator_scan/fast:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/build
.PHONY : storj_emulator_scan/fast

#=============================================================================
# Target rules for targets named storj_emulator

# Build rule for target.
storj_emulator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 storj_emulator
.PHONY : storj_emulator

# fast build rule for target.
storj_emulator/fast:
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/build
.PHONY : storj_emulator/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/main.cpp.s
.PHONY : main.cpp.s

storj/config.o: storj/config.cpp.o

.PHONY : storj/config.o

# target to build an object file
storj/config.cpp.o:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/storj/config.cpp.o
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/storj/config.cpp.o
.PHONY : storj/config.cpp.o

storj/config.i: storj/config.cpp.i

.PHONY : storj/config.i

# target to preprocess a source file
storj/config.cpp.i:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/storj/config.cpp.i
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/storj/config.cpp.i
.PHONY : storj/config.cpp.i

storj/config.s: storj/config.cpp.s

.PHONY : storj/config.s

# target to generate assembly for a file
storj/config.cpp.s:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/storj/config.cpp.s
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/storj/config.cpp.s
.PHONY : storj/config.cpp.s

storj/data_manager.o: storj/data_manager.cpp.o

.PHONY : storj/data_manager.o

# target to build an object file
storj/data_manager.cpp.o:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/storj/data_manager.cpp.o
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/storj/data_manager.cpp.o
.PHONY : storj/data_manager.cpp.o

storj/data_manager.i: storj/data_manager.cpp.i

.PHONY : storj/data_manager.i

# target to preprocess a source file
storj/data_manager.cpp.i:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/storj/data_manager.cpp.i
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/storj/data_manager.cpp.i
.PHONY : storj/data_manager.cpp.i

storj/data_manager.s: storj/data_manager.cpp.s

.PHONY : storj/data_manager.s

# target to generate assembly for a file
storj/data_manager.cpp.s:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/storj/data_manager.cpp.s
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/storj/data_manager.cpp.s
.PHONY : storj/data_manager.cpp.s

storj/data_processor.o: storj/data_processor.cpp.o

.PHONY : storj/data_processor.o

# target to build an object file
storj/data_processor.cpp.o:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/storj/data_processor.cpp.o
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/storj/data_processor.cpp.o
.PHONY : storj/data_processor.cpp.o

storj/data_processor.i: storj/data_processor.cpp.i

.PHONY : storj/data_processor.i

# target to preprocess a source file
storj/data_processor.cpp.i:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/storj/data_processor.cpp.i
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/storj/data_processor.cpp.i
.PHONY : storj/data_processor.cpp.i

storj/data_processor.s: storj/data_processor.cpp.s

.PHONY : storj/data_processor.s

# target to generate assembly for a file
storj/data_processor.cpp.s:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/storj/data_processor.cpp.s
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/storj/data_processor.cpp.s
.PHONY : storj/data_processor.cpp.s

storj/erasure_share.o: storj/erasure_share.cpp.o

.PHONY : storj/erasure_share.o

# target to build an object file
storj/erasure_share.cpp.o:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/storj/erasure_share.cpp.o
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/storj/erasure_share.cpp.o
.PHONY : storj/erasure_share.cpp.o

storj/erasure_share.i: storj/erasure_share.cpp.i

.PHONY : storj/erasure_share.i

# target to preprocess a source file
storj/erasure_share.cpp.i:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/storj/erasure_share.cpp.i
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/storj/erasure_share.cpp.i
.PHONY : storj/erasure_share.cpp.i

storj/erasure_share.s: storj/erasure_share.cpp.s

.PHONY : storj/erasure_share.s

# target to generate assembly for a file
storj/erasure_share.cpp.s:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/storj/erasure_share.cpp.s
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/storj/erasure_share.cpp.s
.PHONY : storj/erasure_share.cpp.s

storj/file.o: storj/file.cpp.o

.PHONY : storj/file.o

# target to build an object file
storj/file.cpp.o:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/storj/file.cpp.o
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/storj/file.cpp.o
.PHONY : storj/file.cpp.o

storj/file.i: storj/file.cpp.i

.PHONY : storj/file.i

# target to preprocess a source file
storj/file.cpp.i:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/storj/file.cpp.i
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/storj/file.cpp.i
.PHONY : storj/file.cpp.i

storj/file.s: storj/file.cpp.s

.PHONY : storj/file.s

# target to generate assembly for a file
storj/file.cpp.s:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/storj/file.cpp.s
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/storj/file.cpp.s
.PHONY : storj/file.cpp.s

storj/piece.o: storj/piece.cpp.o

.PHONY : storj/piece.o

# target to build an object file
storj/piece.cpp.o:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/storj/piece.cpp.o
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/storj/piece.cpp.o
.PHONY : storj/piece.cpp.o

storj/piece.i: storj/piece.cpp.i

.PHONY : storj/piece.i

# target to preprocess a source file
storj/piece.cpp.i:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/storj/piece.cpp.i
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/storj/piece.cpp.i
.PHONY : storj/piece.cpp.i

storj/piece.s: storj/piece.cpp.s

.PHONY : storj/piece.s

# target to generate assembly for a file
storj/piece.cpp.s:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/storj/piece.cpp.s
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/storj/piece.cpp.s
.PHONY : storj/piece.cpp.s

storj/segment.o: storj/segment.cpp.o

.PHONY : storj/segment.o

# target to build an object file
storj/segment.cpp.o:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/storj/segment.cpp.o
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/storj/segment.cpp.o
.PHONY : storj/segment.cpp.o

storj/segment.i: storj/segment.cpp.i

.PHONY : storj/segment.i

# target to preprocess a source file
storj/segment.cpp.i:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/storj/segment.cpp.i
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/storj/segment.cpp.i
.PHONY : storj/segment.cpp.i

storj/segment.s: storj/segment.cpp.s

.PHONY : storj/segment.s

# target to generate assembly for a file
storj/segment.cpp.s:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/storj/segment.cpp.s
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/storj/segment.cpp.s
.PHONY : storj/segment.cpp.s

storj/storage_node.o: storj/storage_node.cpp.o

.PHONY : storj/storage_node.o

# target to build an object file
storj/storage_node.cpp.o:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/storj/storage_node.cpp.o
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/storj/storage_node.cpp.o
.PHONY : storj/storage_node.cpp.o

storj/storage_node.i: storj/storage_node.cpp.i

.PHONY : storj/storage_node.i

# target to preprocess a source file
storj/storage_node.cpp.i:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/storj/storage_node.cpp.i
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/storj/storage_node.cpp.i
.PHONY : storj/storage_node.cpp.i

storj/storage_node.s: storj/storage_node.cpp.s

.PHONY : storj/storage_node.s

# target to generate assembly for a file
storj/storage_node.cpp.s:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/storj/storage_node.cpp.s
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/storj/storage_node.cpp.s
.PHONY : storj/storage_node.cpp.s

storj/stripe.o: storj/stripe.cpp.o

.PHONY : storj/stripe.o

# target to build an object file
storj/stripe.cpp.o:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/storj/stripe.cpp.o
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/storj/stripe.cpp.o
.PHONY : storj/stripe.cpp.o

storj/stripe.i: storj/stripe.cpp.i

.PHONY : storj/stripe.i

# target to preprocess a source file
storj/stripe.cpp.i:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/storj/stripe.cpp.i
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/storj/stripe.cpp.i
.PHONY : storj/stripe.cpp.i

storj/stripe.s: storj/stripe.cpp.s

.PHONY : storj/stripe.s

# target to generate assembly for a file
storj/stripe.cpp.s:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/storj/stripe.cpp.s
	$(MAKE) -f CMakeFiles/storj_emulator.dir/build.make CMakeFiles/storj_emulator.dir/storj/stripe.cpp.s
.PHONY : storj/stripe.cpp.s

test_main.o: test_main.cpp.o

.PHONY : test_main.o

# target to build an object file
test_main.cpp.o:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/test_main.cpp.o
.PHONY : test_main.cpp.o

test_main.i: test_main.cpp.i

.PHONY : test_main.i

# target to preprocess a source file
test_main.cpp.i:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/test_main.cpp.i
.PHONY : test_main.cpp.i

test_main.s: test_main.cpp.s

.PHONY : test_main.s

# target to generate assembly for a file
test_main.cpp.s:
	$(MAKE) -f CMakeFiles/storj_emulator_scan.dir/build.make CMakeFiles/storj_emulator_scan.dir/test_main.cpp.s
.PHONY : test_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... storj_emulator_scan"
	@echo "... storj_emulator"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... storj/config.o"
	@echo "... storj/config.i"
	@echo "... storj/config.s"
	@echo "... storj/data_manager.o"
	@echo "... storj/data_manager.i"
	@echo "... storj/data_manager.s"
	@echo "... storj/data_processor.o"
	@echo "... storj/data_processor.i"
	@echo "... storj/data_processor.s"
	@echo "... storj/erasure_share.o"
	@echo "... storj/erasure_share.i"
	@echo "... storj/erasure_share.s"
	@echo "... storj/file.o"
	@echo "... storj/file.i"
	@echo "... storj/file.s"
	@echo "... storj/piece.o"
	@echo "... storj/piece.i"
	@echo "... storj/piece.s"
	@echo "... storj/segment.o"
	@echo "... storj/segment.i"
	@echo "... storj/segment.s"
	@echo "... storj/storage_node.o"
	@echo "... storj/storage_node.i"
	@echo "... storj/storage_node.s"
	@echo "... storj/stripe.o"
	@echo "... storj/stripe.i"
	@echo "... storj/stripe.s"
	@echo "... test_main.o"
	@echo "... test_main.i"
	@echo "... test_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

